<?php
//THIS IS NOT A FINISHED APPLICATION. JUST A CODING EXAMPLE
$apiurl = 'https://localhost/juice4/vending.php' ; 
$apicclogin = 'admin' ;
$apiccpassword = 'xxxxxxxxx' ; 
$apijclogin = 'admin' ;
$apijcpassword = 'xxxxxxxx' ; 
$brand = 'Juice' ; 
#$logic = array('STS','AMI','AMIDELIVERED','JC','CC','ACH','GIMME5','MULTILANG') ; 
$logic = array('STS','AMI','AMIDELIVERED','JC','CC','ACH','GIMME5',) ; 
$motd = '' ; 
$lang = 'en' ; 
$currency = 'dollars' ; 
$quickpicks = array('20','50','100') ; 
?>